### ISSUE TITLE
fighting against 128 bit types

### ISSUE THREAD

**Issue by tankf33der** [TrustInSoft-CI/TrustInSoft-CI#10]
[bee2](https://github.com/agievich/bee2) is a cryptographic library which implements cryptographic algorithm and protocols standardized in Belarus (additionally digital signature in Russia and Ukraine). C code is heavy, i dont like it.

I've cut hash-only code and created my own [repo](https://github.com/tankf33der/bee2-bash-tis) to run under TIS for fun.
General compilation of main.c code + everything releated by gcc is working by typing **make** inside repo. So my _cut_ is correct in general.

My [problem](https://ci.trust-in-soft.com/projects/tankf33der/bee2-bash-tis/10?page=1&test=1) as usually before is 128bit types:
```
[kernel] Loading configuration file tis.config
[kernel] Configuration successfully loaded.
[kernel] [ 1/71] Parsing TIS_KERNEL_SHARE/libc/__fc_builtin_for_normalization.i (no preprocessing)
[kernel] [ 2/71] Parsing TIS_KERNEL_SHARE/libc/tis_runtime.c (with preprocessing)
[kernel] [ 3/71] Parsing TIS_KERNEL_SHARE/__tis_mkfs.c (with preprocessing)
[kernel] [ 4/71] Parsing TIS_KERNEL_SHARE/mkfs_empty_filesystem.c (with preprocessing)
[kernel] [ 5/71] Parsing b64.c (with preprocessing)
include/bee2/defs.h:273:[kernel] user error: invalid combination of type specifiers:
                     __int128
[kernel] user error: stopping on file "b64.c" that has errors. Add '-kernel-msg-key pp'
                     for preprocessing command.
[kernel] TrustInSoft Kernel aborted: invalid user input.
[info:results:computation] VERIF ERROR: parsing error
```
Of course, CompCert also failed on this.

What is the best way to handle all this?

Thanks in advance.

**Comment by guillaumemillot** [comment]
I think you should allow the gcc language extensions. Can you change your machdep in the tis.config file to "gcc_sparc_64"?

**Comment by tankf33der** [comment]
Indeed.
