### ISSUE TITLE
Trigger analysis from external CI via upload

### ISSUE THREAD

**Issue by tanzislam** [TrustInSoft-CI/TrustInSoft-CI#11]
Hi, I'm wondering if TrustInSoft CI has any plans to support launching analysis via an HTTP POST endpoint. I've got an [existing C++ project](https://github.com/tanzislam/cryptopals) and some opinionated requirements:

- I don't want to commit a `tis.config` or `compile_commands.json` file in my repo, as they duplicate information already in my makefiles. I'd like to generate them as part of my existing CI build (using [`jq`](https://stedolan.github.io/jq/)) instead before launching the analysis.

- I have several open-source dependencies (all also in GitHub.com) as Git submodules, so it is not [self-contained](https://docs.ci.trust-in-soft.com/faq#technical-requirements). I'll need to run `git submodule update --init --recursive` before launching the analysis.

I'm envisioning something like [Coverity Scan](https://scan.coverity.com/travis_ci), where the analysis is launched by uploading a zip file containing the prepared source code to a project-specific URL. (A Travis plugin to abstract away the details is a usability bonus, but not necessary for me.)

**Comment by tanzislam** [comment]
Another possibility (used by [LGTM](https://lgtm.com/help/lgtm/lgtm.yml-configuration-file) and ~~[Muse-Dev](https://docs.muse.dev/docs/repository-configuration/)~~ [Sonatype Lift](https://help.sonatype.com/lift/configuration-reference)) is to allow specifying setup and build commands in the `tis.config` file. The build process on your server will be:

- either watched for invocations to the compiler, using custom `open()`/`exec()` syscalls injected with `LD_PRELOAD`.

- or instrumented to call your analyzer instead of the compiler, using makefile variable overrides.

Alternatively the `tis.config` can have a different command to generate the `compile_commands.json` file in a known location, instead of running the full build. Your analyzer can then use that file as it currently does.

All these approaches will require securing your analysis server/sandbox and its Internet access for safely running outside code, though.

**Comment by guillaumemillot** [comment]
Hi Tanzinul,

Thanks for your interest in TrustInSoft CI and apologies for my late reply as I've been away for a couple of weeks. I'm in charge of the TIS CI tool on the product side.

Your 2 ideas (launch analyses via HTTP POST endpoint + specifying the setup/build commands in the tis.config file) are not in the roadmap yet as we're currently focusing on core features, but we might definitely consider them in the future.

May I ask you if you've already tried TrustInSoft CI on perhaps a reduced use case?

**Comment by tanzislam** [comment]
For now I'll try with [this simpler repo](https://github.com/tanzislam/cryptopals-1) without dependencies. Feel free to close this Issue.

**Comment by guillaumemillot** [comment]
Ok, I'm happy to assist you if needed.

**Comment by tanzislam** [comment]
Thanks! For self-standing projects it's quite straightforward to configure according to the documentation, and it found a couple of UBs that I agree with. 🙂 I found a couple of issues with the analyzer and raised #12 and #13.

**Comment by guillaumemillot** [comment]
Hi Tanzinul, thanks for the update and for trying the tool.
I answered to #12 and #13 with updated [TIS CI results](https://ci.trust-in-soft.com/projects/guillaumemillot/cryptopals-1/2?page=1). I closed the 2 issues, but of course feel free to re-open if needed.

By the way, your analysis assumes a x86-32 platform (default). Are you interested in finding bugs that would occur on other platforms? You can find [here](https://docs.ci.trust-in-soft.com/reference/supported-architectures#list) all the platforms supported by TIS CI.

**Comment by guillaumemillot** [comment]
I noticed that your [test 10](https://ci.trust-in-soft.com/projects/tanzislam/cryptopals-1/7?page=1&test=10) has the status **Invalid property**. The standard says that `rand` should return an integer value between `0` and `RAND_MAX` = 32767. However in your code `rand` can return a value greater than `RAND_MAX` hence the alarm:

![image](https://user-images.githubusercontent.com/10330584/92263203-892f0f80-eedc-11ea-96ed-a8684e89a7f0.png)

Click Explore and wait for the analysis time (few minutes on this test) to see the exact same thing. I can help you go through it if you're interested.

**Comment by guillaumemillot** [comment]
I'm closing the issue. Feel free to ask more questions.

**Comment by tanzislam** [comment]
One small request: consider accepting an alternate config filename of `.tis.config` (with a leading `.` character). That allows it to be hidden by default in a `ls` listing of the project files. (Most other code-scanning apps in the GitHub Marketplace already do this.)
