### ISSUE TITLE
Conflict with POSIX encrypt() even without #include <unistd.h>

### ISSUE THREAD

**Issue by tanzislam** [TrustInSoft-CI/TrustInSoft-CI#13]
[Test 23](https://ci.trust-in-soft.com/projects/tanzislam/cryptopals-1/6?page=2&test=23) failed with Link Error for an incompatible signature of `encrypt()` between:

- [POSIX's `encrypt()`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/encrypt.html), which is not used in this project as `<unistd.h>` is never `#include`-ed in this project
- this project's [own function called `encrypt()`](https://github.com/tanzislam/cryptopals-1/blob/master/mcp24.c#L15-L21).

Not sure why the analyzer is looking into the POSIX header. Is it getting transitively `#include`-ed via one of the other C standard library headers? Is this meant as a warning?

**Comment by guillaumemillot** [comment]
That is a good question.. `<unistd.h>` is by default included by the TIS CI runtime, that is why there is a conflict.

As workaround, I suggest that you change the `encrypt()` function name in your program for TIS CI only. You can use the `__TRUSTINSOFT_ANALYZER__` macro for this. See `util-1.h`:
https://github.com/tanzislam/cryptopals-1/compare/master...guillaumemillot:tis
