### ISSUE TITLE
My feature requests

### ISSUE THREAD

**Issue by tankf33der** [TrustInSoft-CI/TrustInSoft-CI#4]
Now I understand what features I would implement If I have my own TIS CI. Since you dont have features at all I feel the pure art and fun :)
- manual start, if input of checkout commit's hash is empty then take HEAD
- run job automatically weekly or monthly only if commit happened in this period, let me dont run job(s) on every commit
- dont store jobs results if all greens or store latest 10.
- notify by email or open issue on github (requires access setup) if any non green tests found

You can have any defaults for all above, but let me modify settings I want.

Close issue after reading.

**Comment by guillaumemillot** [comment]
Thanks Mike, closing it. I'll get back to you on some of these features over email.
