### ISSUE TITLE
wrong paging for tests

### ISSUE THREAD

**Issue by tankf33der** [TrustInSoft-CI/TrustInSoft-CI#6]
As you can see [here](https://ci.trust-in-soft.com/projects/tankf33der/monocypher-tis-ci/51?page=24) latest page is empty because (460 mod 20) is zero. Fix it how you feel it.

**Comment by guillaumemillot** [comment]
Thanks, we've indeed noticed a few issues related to pagination. I'll add this one to the list.

**Comment by guillaumemillot** [comment]
We've just released a few bug fixes. The last page is now really the last page:
https://ci.trust-in-soft.com/projects/tankf33der/monocypher-tis-ci/51?page=23

[Link to changelog
](https://docs.ci.trust-in-soft.com/changelog)
