### ISSUE TITLE
wrong filtering and pagging 

### ISSUE THREAD

**Issue by tankf33der** [TrustInSoft-CI/TrustInSoft-CI#7]
How to repeat:
1. open [link](https://ci.trust-in-soft.com/projects/tankf33der/monocypher1-tis/6?page=1)
2. go to latest [page](https://ci.trust-in-soft.com/projects/tankf33der/monocypher1-tis/6?page=14)
3. select "Undefined behavior" to filter
4. you will see empty page and wrong paging on the left:
```
261-4 of 4 tests
```
5. go to first page and you will see 4 failed tests.

**Comment by guillaumemillot** [comment]
Thanks again, it's in our Todo list. I'll close the issue when it's done.

**Comment by guillaumemillot** [comment]
Closing the issue as we've just released a fix. [Link to changelog](https://docs.ci.trust-in-soft.com/changelog)
