### ISSUE TITLE
SSL web server configuration

### ISSUE THREAD

**Issue by tankf33der** [TrustInSoft-CI/TrustInSoft-CI#8]
Main [trust-in-soft](https://trust-in-soft.com) site has [A+](https://www.ssllabs.com/ssltest/analyze.html?d=trust-in-soft.com&hideResults=on) grade from [ssllabs](https://ssllabs.com) scanner. 

At the same time [CI](https://ci.trust-in-soft.com) portal has [B](https://www.ssllabs.com/ssltest/analyze.html?d=ci.trust-in-soft.com&hideResults=on).  Fix it, be cool.

**Comment by guillaumemillot** [comment]
Thanks, we'll take a look and come back to you.

**Comment by guillaumemillot** [comment]
The team updated the library(ies) so now TIS CI portal gets the [A+](https://www.ssllabs.com/ssltest/analyze.html?d=ci.trust-in-soft.com&hideResults=on) grade.

I'm closing the issue. Feel free to re-open.
